services:
  php:
    build:
      context: ./dockerfiles/php
    container_name: echat-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  nginx:
    build:
      context: ./dockerfiles/nginx
    container_name: echat-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  node:
    image: node:20-alpine
    container_name: echat-node
    working_dir: /var/www
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run build"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    restart: unless-stopped

  echo:
    build:
      context: ./dockerfiles/echo
    container_name: echat-echo
    working_dir: /var/www
    environment:
      - APP_URL=${APP_URL:-http://localhost}
      - ECHO_PROTOCOL=http
      - ECHO_REDIS_HOST=redis
      - ECHO_REDIS_PORT=6379
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: echat-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${DB_DATABASE:-laravel}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: echat-redis
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:

